### ISSUE TITLE
How to send only one channel?

### ISSUE THREAD

**Issue by krupaw2** [YoshiRi/PyDMX#1]
Hello,

When i send 
dmx.set_data(1,255) 
then the other channels are set to zero.
Is it possible to drive only one channel?

**Comment by YoshiRi** [comment]
@krupaw2 

Hi.  Thanks for your comment.

I assumed to use DMX512 so the default channel number was 512.
So, I just updated program so that you can control the channel number.

If you want to send only one channel, try to use `Cnumber` options like below.

```python
mydmx = PyDMX('COM3',Cnumber=1)
```

I am glad if you tell me whether it fits and works for your purpose.

**Comment by krupaw2** [comment]
Thank you for your response.
I am using DMX to control 10 RGB stripes, which is 30 channels.

Using your code I was hoping to be able to send a change to one channel without affecting the others.

For example, I have 30 channels set:
255 2 3 4 5 6 7 8 9 10 255 12 13 14 15 16 17 18 190 20 21 22 23 24 25 26 27 255 29 20

I wanted after sending:
dmx.set_data (10,255)
such result:
255 2 3 4 5 6 7 8 9 **255** 255 12 13 14 15 16 17 18 190 20 21 22 23 24 25 26 27 255 29 20

but the result is:
0 0 0 0 0 0 0 0 0 255 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0

After a short analysis, however, it seems to me that the DMX512 specification alone does not allow me to get what I expect - am I right?

**Comment by YoshiRi** [comment]
@krupaw2 

fmm... that's weired.
As long as I tried, this program do not refresh data like your example.

How did you check the result?

Here is my trial and it seems that it do not refresh the past value.

```py
>>> from PyDMX import PyDMX
>>> dmx = PyDMX(Cnumber=30)
>>> dmx.set_random_data()
>>> dmx.data
array([  0,  42, 135, 183,  25, 211, 187, 128, 207,   6,  18,  39, 229,
        93,  85, 229, 230, 149,  84, 159, 162, 134, 205, 224,  52,  34,
       216, 108, 186, 151,  61], dtype=uint8)
>>> dmx.set_data(1,5)
>>> dmx.data
array([  0,   5, 135, 183,  25, 211, 187, 128, 207,   6,  18,  39, 229,
        93,  85, 229, 230, 149,  84, 159, 162, 134, 205, 224,  52,  34,
       216, 108, 186, 151,  61], dtype=uint8)
```

**Comment by krupaw2** [comment]
When i try it in console all is OK.

I wanted to use this to control my RGB stripes in Domoticz with bash. 

I added to the script:
if __name__ == '__main__':
    dmx = PyDMX('/dev/ttyUSB1',Cnumber=512)
    ch = int(sys.argv[1])
    val = int(sys.argv[2])
    dmx.set_data(ch,val)

And I run e.g.:
python3 PyDMXpy 4 255

And then it works as I wrote above, that only changes the value of this channel and sets the rest to zero.

Your script is OK, only I can't use it for what I need :)

**Comment by YoshiRi** [comment]
OK. I got your problem. 
The past dmx data is saved as  class variable, so it always refreshed when run from bash.

I updated my program to use txt file to save and load past DMX data.
Update your repository and just rewrite your code as following:

```
dmx = PyDMX('/dev/ttyUSB1',use_prev_data=True)
```

It will generate `preserved_data.txt` when you finish your first program, which preserve your last DMX data.
Go for it!

**Comment by krupaw2** [comment]
Thank you very much for help.
I finally got it working :)

I had to change(wrong quotation mark and data format in you file):
self.data = np.loadtxt(self.preserve_data_name,dtype=’int’)
to
self.data = np.loadtxt(self.preserve_data_name,dtype='uint8')

and uncomment

#self.ser = serial.Serial(COM,baudrate=Brate,bytesize=Bsize,stopbits=StopB)

Now it works perfectly for my application.

But I don't like the file format yet :)
Is it possible to switch from: 
0.000000000000000000e+00
1.960000000000000000e+02
2.410000000000000000e+02
2.110000000000000000e+02
2.310000000000000000e+02
1.100000000000000000e+02 

to:
0
196
241
211
231
110?

Thank you very much again for your quick help.

**Comment by YoshiRi** [comment]
> I had to change(wrong quotation mark and data format in you file):

sorry, that was my mistake. I fix it.

> Thank you very much again for your quick help.

Yeah. I also learned a lot. Thanks for your comments.
