### ISSUE TITLE
PyDMX.py line 59 - ’int’ with wrong apostrophes  

### ISSUE THREAD

**Issue by TruckDweller** [YoshiRi/PyDMX#2]
Hello, 

while using your code on a ubuntu based system with python 3.8, line 59 of PyDMX.py produced an error due to apostrophes ’ 
Using apostrophe ' as already used in line 55 works fine. 

Best regards, 

TruckDweller

**Comment by YoshiRi** [comment]
Just fixed the part you mentioned.
Thanks!

Yoshi
